version: '2'
services:
    print_management-app:
        image: print_management
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://print_management-mysql:3306/print_management?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    print_management-mysql:
        extends:
            file: mysql.yml
            service: print_management-mysql
